apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-p1
  template:
    metadata:
      labels:
        app: producer-p1
    spec:
      containers:
      - name: producer-p1
        image: github.com/weak-head/go-kafka-test/producer:0.0.1
        env:
        - name: kafkaURL
          value: ""
        - name: topic
          value: "zeus"
        - name: prefix
          value: "p1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-p2
  template:
    metadata:
      labels:
        app: producer-p2
    spec:
      containers:
      - name: producer-p2
        image: github.com/weak-head/go-kafka-test/producer:0.0.1
        env:
        - name: kafkaURL
          value: ""
        - name: topic
          value: "zeus"
        - name: prefix
          value: "p2"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m